export const db = [
  { name: 'Red Rocket', year: 2021 },
  { name: 'The Wolf of Wall Street', year: 2013 },
  { name: 'Pleasure', year: 2021 },
  { name: 'Love (II)', year: 2015 },
  { name: 'Fight Club', year: 1999 },
  { name: 'American Psycho', year: 2000 },
  { name: 'Hustlers', year: 2019 },
  { name: 'Boogie Nights', year: 1997 },
  { name: 'The Blue Lagoon', year: 1980 },
  { name: 'Into the Wild', year: 2007 },
  { name: 'A Clockwork Orange', year: 1971 },
  { name: 'City of God', year: 2002 },
  { name: 'Malena', year: 2000 },
  { name: 'Nymphomaniac: Vol. I', year: 2013 },
  { name: 'American History X', year: 1998 },
  { name: 'Blue Is the Warmest Colour', year: 2013 },
  { name: 'Suspiria (I)', year: 2018 },
  { name: 'Red Sparrow', year: 2018 },
  { name: 'Forgetting Sarah Marshall', year: 2008 },
  { name: 'Step Brothers', year: 2008 },
  { name: 'Irreversible', year: 2002 },
  { name: 'Magic Mike', year: 2012 },
  { name: 'Dirty Grandpa', year: 2016 },
  { name: 'Salò, or the 120 Days of Sodom', year: 1975 },
  { name: 'A Serbian Film', year: 2010 },
  { name: 'Cannibal Holocaust', year: 1980 },
  { name: 'EuroTrip', year: 2004 },
  { name: 'What We Do in the Shadows', year: 2014 },
  { name: '9 Songs', year: 2004 },
  { name: 'Captain Fantastic', year: 2016 },
  { name: 'Movie 43', year: 2013 },
  { name: 'Hall Pass', year: 2011 },
  { name: 'Red Dragon', year: 2002 },
  { name: 'Antichrist', year: 2009 },
  { name: 'The Dictator', year: 2012 },
  { name: 'Minari', year: 2020 },
  { name: "There's Something About Mary", year: 1998 },
  { name: 'Below Her Mouth', year: 2016 },
  { name: 'An American Werewolf in London', year: 1981 },
  { name: 'Y tu mamá también', year: 2001 },
  { name: 'The Wedding Planner', year: 2001 },
  { name: 'Ace Ventura: Pet Detective', year: 1994 },
  { name: 'Gattaca', year: 1997 },
  { name: 'Mandy (I)', year: 2018 },
  { name: 'Verónica (I)', year: 2017 },
  { name: 'American Reunion', year: 2012 },
  { name: 'Little Children', year: 2006 },
  { name: 'Sex and Lucía', year: 2001 },
  { name: 'Enter the Void', year: 2009 },
  { name: 'Nymphomaniac: Vol. II', year: 2013 },
  { name: 'Waiting... (I)', year: 2005 },
  { name: 'The Holy Mountain', year: 1973 },
  { name: 'Betty Blue', year: 1986 },
  { name: 'Roma', year: 2018 },
  { name: 'Paul', year: 2011 },
  { name: 'Dogville', year: 2003 },
  { name: 'Scouts Guide to the Zombie Apocalypse', year: 2015 },
  { name: 'Vacation (I)', year: 2015 },
  { name: 'Changeling', year: 2008 },
  { name: 'The Secret in Their Eyes', year: 2009 },
  { name: 'Love Lessons', year: 1995 },
  { name: 'Inside Llewyn Davis', year: 2013 },
  { name: 'Blood In, Blood Out', year: 1993 },
  { name: 'Sorry to Bother You', year: 2018 },
  { name: 'Jarhead', year: 2005 },
  {
    name: 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan',
    year: 2006,
  },
  { name: 'Sex and Zen', year: 1991 },
  { name: 'Swiss Army Man', year: 2016 },
  { name: 'Before Sunset', year: 2004 },
  { name: 'Any Given Sunday', year: 1999 },
  { name: 'Role Models', year: 2008 },
  { name: 'Life of Brian', year: 1979 },
  { name: 'Zack and Miri Make a Porno', year: 2008 },
  { name: 'Diet of Sex', year: 2014 },
  { name: 'Pain and Glory', year: 2019 },
  { name: 'City Hunter', year: 2018 },
  { name: 'The Voyeur', year: 1994 },
  { name: 'About a Boy', year: 2002 },
  { name: 'Before Midnight', year: 2013 },
  { name: 'Definitely, Maybe', year: 2008 },
  { name: 'In the Realm of the Senses', year: 1976 },
  { name: '40 Days and 40 Nights', year: 2002 },
  { name: 'Killer Joe', year: 2011 },
  { name: 'Frankenstein', year: 1994 },
  { name: 'Lovelace', year: 2013 },
  { name: 'CHIPS', year: 2017 },
  { name: 'My Own Private Idaho', year: 1991 },
  { name: "You Don't Mess with the Zohan", year: 2008 },
  { name: 'Curiosa', year: 2019 },
  { name: 'Wet Hot American Summer', year: 2001 },
  { name: 'The Wicker Man', year: 1973 },
  { name: 'The Crying Game', year: 1992 },
  { name: 'The Cook, the Thief, His Wife & Her Lover', year: 1989 },
  { name: 'Hard Candy', year: 2005 },
  { name: 'The Hot Chick', year: 2002 },
  { name: 'American Honey', year: 2016 },
  { name: 'Wij', year: 2018 },
  { name: 'Ma (I)', year: 2019 },
  { name: 'Mommy (I)', year: 2014 },
  { name: 'Now & Later', year: 2009 },
  { name: 'Frivolous Lola', year: 1998 },
  { name: 'One Hour Photo', year: 2002 },
  { name: 'Made of Honor', year: 2008 },
  { name: 'Teeth (I)', year: 2007 },
  { name: 'American Mary', year: 2012 },
  { name: 'Piranha 3DD', year: 2012 },
  { name: 'Black Book', year: 2006 },
  { name: 'The Full Monty', year: 1997 },
  { name: 'I Spit on Your Grave 2', year: 2013 },
  { name: 'Bitter Moon', year: 1992 },
  { name: 'White Girl', year: 2016 },
  { name: 'The Beach Bum', year: 2019 },
  { name: 'A Dirty Shame', year: 2004 },
  { name: 'Diary of a Nymphomaniac', year: 2008 },
  { name: 'Jamón, Jamón', year: 1992 },
  { name: "God's Own Country", year: 2017 },
  { name: 'All the Right Moves', year: 1983 },
  { name: 'Dolemite Is My Name', year: 2019 },
  { name: 'An Awkward Sexual Adventure', year: 2012 },
  { name: 'Ken Park', year: 2002 },
  { name: 'Little Fockers', year: 2010 },
  { name: 'Popstar: Never Stop Never Stopping', year: 2016 },
  { name: 'Horns', year: 2013 },
  { name: 'The Rules of Attraction', year: 2002 },
  { name: '50/50', year: 2011 },
  { name: 'All About My Mother', year: 1999 },
  { name: 'Mary and Max', year: 2009 },
  { name: 'Southland Tales', year: 2006 },
  { name: 'Young Adult', year: 2011 },
  { name: 'Freddy Got Fingered', year: 2001 },
  { name: 'How to Lose Friends & Alienate People', year: 2008 },
  { name: 'Flower (I)', year: 2017 },
  { name: 'Starlet (I)', year: 2012 },
  { name: 'Inventing the Abbotts', year: 1997 },
  { name: 'The Simpsons Movie', year: 2007 },
  { name: 'Quills', year: 2000 },
  { name: 'Bad Lieutenant', year: 1992 },
  { name: 'Secret Things', year: 2002 },
  { name: 'Fat Girl', year: 2001 },
  { name: 'Night of the Demon', year: 1980 },
  { name: 'Ghost Town (I)', year: 2008 },
  { name: 'Reign Over Me', year: 2007 },
  { name: 'Ginger Snaps', year: 2000 },
  { name: 'Breakfast on Pluto', year: 2005 },
  { name: 'American Wedding', year: 2003 },
  { name: 'Savage Grace', year: 2007 },
  { name: 'Human Centipede 2: Tom Six Discusses the Story Concept', year: 2011 },
  { name: 'A Bigger Splash', year: 2015 },
  { name: 'Nowhere Boy', year: 2009 },
  { name: 'Harsh Times', year: 2005 },
  { name: 'Detroit Rock City', year: 1999 },
  { name: 'The Snowtown Murders', year: 2011 },
  { name: '1900', year: 1976 },
  { name: 'Ali G Indahouse', year: 2002 },
  { name: 'The Kids Are All Right', year: 2010 },
  { name: 'Border', year: 2018 },
  { name: 'Double Lover', year: 2017 },
  { name: 'The Broken Hearts Gallery', year: 2020 },
  { name: 'American Gigolo', year: 1980 },
  { name: 'Bang Gang: A Modern Love Story', year: 2015 },
  { name: 'The Ice Storm', year: 1997 },
  { name: 'For Your Consideration', year: 2006 },
  { name: 'Fallo!', year: 2003 },
  { name: 'The Untamed', year: 2016 },
  { name: 'North Country', year: 2005 },
  { name: 'A Million Little Pieces', year: 2018 },
  { name: 'Table 19', year: 2017 },
  { name: 'The Good Girl', year: 2002 },
  { name: 'Holy Motors', year: 2012 },
  { name: 'Thirst', year: 2009 },
  { name: 'Altered States', year: 1980 },
  { name: 'Shallow Grave', year: 1994 },
  { name: 'Maps to the Stars', year: 2014 },
  { name: 'Hunger', year: 2008 },
  { name: 'Rocco', year: 2016 },
  { name: 'Baise-moi', year: 2000 },
  { name: 'The Decameron', year: 1971 },
  { name: 'John Dies at the End', year: 2012 },
  { name: 'Young Adam', year: 2003 },
  { name: "L'ennui", year: 1998 },
  { name: 'Youth in Revolt', year: 2009 },
  { name: 'Prime', year: 2005 },
  { name: 'Nekromantik', year: 1988 },
  { name: 'Fifty Shades of Black', year: 2016 },
  { name: 'Cannibal Ferox', year: 1981 },
  { name: "Billy Lynn's Long Halftime Walk", year: 2016 },
  { name: 'Women in Love', year: 1969 },
  { name: 'Pink Narcissus', year: 1971 },
  { name: 'River of Fundament', year: 2014 },
  { name: 'Fellini Satyricon', year: 1969 },
  { name: 'Thriller: A Cruel Picture', year: 1973 },
  { name: 'Creep 2', year: 2017 },
  { name: 'Four Lovers', year: 2010 },
  { name: 'Human Traffic', year: 1999 },
  { name: 'Soul Plane', year: 2004 },
  { name: 'Wristcutters: A Love Story', year: 2006 },
  { name: 'Arabian Nights', year: 1974 },
  { name: 'Flesh Gordon', year: 1974 },
  { name: 'Life as a House', year: 2001 },
  { name: 'Suntan', year: 2016 },
  { name: 'Barry Munday', year: 2010 },
  { name: 'Free Fall (I)', year: 2013 },
  { name: 'Toni Erdmann', year: 2016 },
  { name: 'The Golden Glove', year: 2019 },
  { name: 'The Night Before (II)', year: 2015 },
  { name: 'The Beast', year: 1975 },
  { name: 'Man Bites Dog', year: 1992 },
  { name: "Angela's Ashes", year: 1999 },
  { name: 'Bubba Ho-Tep', year: 2002 },
  { name: 'Midori', year: 1992 },
  { name: 'Dear Mother', year: 2020 },
  { name: 'The Recruit', year: 2003 },
  { name: 'Bliss', year: 1997 },
  { name: 'The Overnight', year: 2015 },
  { name: 'Valentino', year: 1977 },
  { name: 'The Love Guru', year: 2008 },
  { name: 'Party Monster', year: 2003 },
  { name: 'Deuce Bigalow: European Gigolo', year: 2005 },
  { name: 'Choke', year: 2008 },
  { name: 'Dry Wind', year: 2020 },
  { name: '11:14', year: 2003 },
  { name: 'Nowhere', year: 1997 },
  { name: "It's a Boy Girl Thing", year: 2006 },
  { name: 'Wonderland', year: 2003 },
  { name: 'Stranger by the Lake', year: 2013 },
  { name: 'Girl (II)', year: 2018 },
  { name: '7 Days', year: 2010 },
  { name: 'We Are the Flesh', year: 2016 },
  { name: 'Murmur of the Heart', year: 1971 },
  { name: 'Jungle Holocaust', year: 1977 },
  { name: 'Diner', year: 1982 },
  { name: 'Accidental Love', year: 2015 },
  { name: 'La tutora', year: 2016 },
  { name: 'I Am Curious (Yellow)', year: 1967 },
  { name: 'The Key', year: 1983 },
  { name: 'Wake in Fright', year: 1971 },
  { name: 'The Red Pill', year: 2016 },
  { name: 'Turkish Delight', year: 1973 },
  { name: 'The Prince', year: 2019 },
  { name: 'Love Exposure', year: 2008 },
  { name: 'The Believer', year: 2001 },
  { name: 'Belladonna of Sadness', year: 1973 },
  { name: 'Bad Milo', year: 2013 },
  { name: 'Miranda', year: 1985 },
  { name: 'The Bitter Tears of Petra von Kant', year: 1972 },
  { name: 'The Jane Austen Book Club', year: 2007 },
  { name: 'Street Trash', year: 1987 },
  { name: 'The Survivalist', year: 2015 },
  { name: 'High Heels', year: 1991 },
  { name: 'Airplane Mode (II)', year: 2019 },
  { name: 'Salon Kitty', year: 1976 },
  { name: 'Putney Swope', year: 1969 },
  { name: 'The Greasy Strangler', year: 2016 },
  { name: 'The Libertine', year: 2004 },
  { name: 'Sweet Movie', year: 1974 },
  { name: 'The Cooler', year: 2003 },
  { name: 'The Canterbury Tales', year: 1972 },
  { name: 'Slackers', year: 2002 },
  { name: 'The Door in the Floor', year: 2004 },
  { name: 'Death to Smoochy', year: 2002 },
  { name: 'Unfinished Business (I)', year: 2015 },
  { name: 'Deathgasm', year: 2015 },
  { name: 'A Real Young Girl', year: 1976 },
  { name: 'Spetters', year: 1980 },
  { name: 'Tideland', year: 2005 },
  { name: 'A Field in England', year: 2013 },
  { name: 'The Doom Generation', year: 1995 },
  { name: 'Miss March', year: 2009 },
  { name: 'Bent', year: 1997 },
  { name: 'Postal', year: 2007 },
  { name: 'Wetlands', year: 2013 },
  { name: 'Bamboozled', year: 2000 },
  { name: 'Charlie Countryman', year: 2013 },
  { name: 'Poolhall Junkies', year: 2002 },
  { name: 'Tromeo and Juliet', year: 1996 },
  { name: 'Lila dit ça', year: 2004 },
  { name: 'Everything Is Illuminated', year: 2005 },
  { name: 'Equus', year: 1977 },
  { name: 'Up!', year: 1976 },
  { name: "Soldier's Girl", year: 2003 },
  { name: 'The Climb', year: 2019 },
  { name: 'Begotten', year: 1989 },
  { name: 'Made in Dagenham', year: 2010 },
  { name: 'Paris 05:59: Théo & Hugo', year: 2016 },
  { name: 'A Guide to Recognizing Your Saints', year: 2006 },
  { name: 'Pieles', year: 2017 },
  { name: 'Slaughterhouse-Five', year: 1972 },
  { name: 'The Dance of Reality', year: 2013 },
  { name: 'Female Trouble', year: 1974 },
  { name: 'The Aristocrats', year: 2005 },
  { name: 'Moebius', year: 2013 },
  { name: 'Cyrus (I)', year: 2010 },
  { name: 'Hide & Seek (I)', year: 2014 },
  { name: "Tim and Eric's Billion Dollar Movie", year: 2012 },
  { name: 'Europa Europa', year: 1990 },
  { name: 'Sebastiane', year: 1976 },
  { name: 'What Have I Done to Deserve This?', year: 1984 },
  { name: 'The Club', year: 2015 },
  { name: 'Hollywoodland', year: 2006 },
  { name: 'XXY', year: 2007 },
  { name: 'The Science of Sleep', year: 2006 },
  { name: 'Devil in the Flesh', year: 1986 },
  { name: 'Hard to Be a God', year: 2013 },
  { name: 'Miracle at St. Anna', year: 2008 },
  { name: 'Hesher', year: 2010 },
  { name: 'The Devils', year: 2002 },
  { name: 'Another Gay Movie', year: 2006 },
  { name: 'Sauvage / Wild', year: 2018 },
  { name: 'Dick: The Documentary', year: 2013 },
  { name: 'Red Road', year: 2006 },
  { name: 'Junebug', year: 2005 },
  { name: 'Tokyo Gore Police', year: 2008 },
  { name: 'Urotsukidoji: Legend of the Overfiend', year: 1989 },
  { name: 'Naples in Veils', year: 2017 },
  { name: 'My Life as a Dog', year: 1985 },
  { name: 'Guardami', year: 1999 },
  { name: 'Ma ma', year: 2015 },
  { name: "I'm Still Here (I)", year: 2010 },
  { name: 'Slaughter High', year: 1986 },
  { name: 'Synonyms', year: 2019 },
  { name: 'Victor Crowley', year: 2017 },
  { name: 'Bijitâ Q', year: 2001 },
  { name: "It's All Gone Pete Tong", year: 2004 },
  { name: 'The 4th Man', year: 1983 },
  { name: 'Neon Bull', year: 2015 },
  { name: 'Breakfast of Champions', year: 1999 },
  { name: 'Running with Scissors', year: 2006 },
  { name: 'Fermo posta Tinto Brass', year: 1995 },
  { name: 'The Matador', year: 2005 },
  { name: 'Tokyo!', year: 2008 },
  { name: 'Taxidermia', year: 2006 },
  { name: 'Aquarius (I)', year: 2016 },
  { name: 'Barnens ö', year: 1980 },
  { name: 'Lisztomania', year: 1975 },
  { name: 'The New Girlfriend', year: 2014 },
  { name: 'Envy', year: 2004 },
  { name: 'Strange Wilderness', year: 2008 },
  { name: 'The Pillow Book', year: 1996 },
  { name: 'Fantasías', year: 2003 },
  { name: 'Swearnet: The Movie', year: 2014 },
  { name: 'Confetti', year: 2006 },
  { name: 'The Specials', year: 2000 },
  { name: 'Flawless', year: 1999 },
  { name: 'Lazy Hazy Crazy', year: 2015 },
  { name: 'Hawaii (I)', year: 2013 },
  { name: 'The Acrobat', year: 2019 },
  { name: 'Lawn Dogs', year: 1997 },
  { name: 'Cold Prey', year: 2006 },
  { name: 'Assimilate (I)', year: 2019 },
  { name: 'O Fantasma', year: 2000 },
  { name: 'Immoral Women', year: 1979 },
  { name: 'Inside Deep Throat', year: 2005 },
  { name: 'Marfa Girl 2', year: 2018 },
  { name: 'Daisy Diamond', year: 2007 },
  { name: '9 to 5: Days in Porn', year: 2008 },
  { name: 'The Shape of Things', year: 2003 },
  { name: 'Rogue Trader', year: 1999 },
  { name: 'Strippers vs Werewolves', year: 2012 },
  { name: 'Pasolini', year: 2014 },
  { name: 'A Moment in the Reeds', year: 2017 },
  { name: 'Happy Endings', year: 2005 },
  { name: 'Endless Poetry', year: 2016 },
  { name: 'Wolfen', year: 1981 },
  { name: 'Eleven Days, Eleven Nights', year: 1987 },
  { name: 'An Eye for Beauty', year: 2014 },
  { name: 'Animal Factory', year: 2000 },
  { name: 'The Killing Gene', year: 2007 },
  { name: 'Carried Away', year: 1996 },
  { name: '3-D Sex and Zen: Extreme Ecstasy', year: 2011 },
  { name: 'Lone Star State of Mind', year: 2002 },
  { name: 'The Onion Movie', year: 2008 },
  { name: 'Being Julia', year: 2004 },
  { name: 'The Bad Education Movie', year: 2015 },
  { name: 'Felicity', year: 1978 },
  { name: 'The Reivers', year: 1969 },
  { name: 'Tape', year: 2001 },
  { name: 'The Statement', year: 2003 },
  { name: 'Nude Nuns with Big Guns', year: 2010 },
  { name: 'I Want Your Love', year: 2012 },
  { name: 'Stage Beauty', year: 2004 },
  { name: 'Paradise: Love', year: 2012 },
  { name: 'Solo (IV)', year: 2013 },
  { name: 'Emmanuelle II', year: 1975 },
  { name: 'Citizen Toxie: The Toxic Avenger IV', year: 2000 },
  { name: 'The Winter Guest', year: 1997 },
  { name: 'Teach Me Tonight', year: 1997 },
  { name: 'Alucarda', year: 1977 },
  { name: 'Art School Confidential', year: 2006 },
  { name: 'Tomboy', year: 1985 },
  { name: 'Jalla! Jalla!', year: 2000 },
  { name: 'The Mudge Boy', year: 2003 },
  { name: 'Sex and Breakfast', year: 2005 },
  { name: 'The Commune', year: 2016 },
  { name: 'The Ten', year: 2007 },
  { name: 'To the Ends of the World', year: 2018 },
  { name: 'Tiny Furniture', year: 2010 },
  { name: 'Intermission', year: 2003 },
  { name: 'Goodbye Uncle Tom', year: 1971 },
  { name: 'Gutterballs', year: 2008 },
  { name: 'Young & Wild', year: 2012 },
  { name: 'German Angst', year: 2015 },
  { name: 'Trick', year: 1999 },
  { name: 'House of Flesh Mannequins', year: 2009 },
  { name: "Rory O'Shea Was Here", year: 2004 },
  { name: 'Finding Bliss', year: 2009 },
  { name: 'Bad Johnson', year: 2014 },
  { name: 'Drowning by Numbers', year: 1988 },
  { name: 'Spring Awakening', year: 2015 },
  { name: 'The Mother and the Whore', year: 1973 },
  { name: 'Symbol', year: 2009 },
  { name: 'Autoerotic', year: 2011 },
  { name: 'Another Day in Paradise', year: 1998 },
  { name: 'Boogie Woogie', year: 2009 },
  { name: 'Totally F***ed Up', year: 1993 },
  { name: 'Godard Mon Amour', year: 2017 },
  { name: 'Nekromantik 2', year: 1991 },
  { name: 'Ex Drummer', year: 2007 },
  { name: 'Waterland', year: 1992 },
  { name: 'Schizopolis', year: 1996 },
  { name: 'Eating Out (I)', year: 2004 },
  { name: 'The Decline of the American Empire', year: 1986 },
  { name: 'Cabin Fever 2: Spring Fever', year: 2009 },
  { name: 'Antibodies', year: 2005 },
  { name: 'Gloria (II)', year: 2013 },
  { name: 'Love Strange Love', year: 1982 },
  { name: "This Girl's Life", year: 2003 },
  { name: 'Religulous', year: 2008 },
  { name: 'Out of Nature', year: 2014 },
  { name: 'Sans Soleil', year: 1983 },
  { name: 'Rape Zombie: Lust of the Dead', year: 2012 },
  { name: 'The Wild Boys', year: 2017 },
  { name: "We Don't Live Here Anymore", year: 2004 },
  { name: 'The Ruling Class', year: 1972 },
  { name: 'Warrior Queen', year: 1987 },
  { name: 'The Editor', year: 2014 },
  { name: 'The Black Room', year: 2017 },
  { name: 'Lady Chatterley', year: 2006 },
  { name: 'Last Stop on the Night Train', year: 1975 },
  { name: 'La marge', year: 1976 },
  { name: 'The Oh in Ohio', year: 2006 },
  { name: 'Come Undone', year: 2000 },
  { name: 'Staying Vertical', year: 2016 },
  { name: '8 ½ Women', year: 1999 },
  { name: 'Arrebato', year: 1979 },
  { name: 'Meat', year: 2010 },
  { name: 'Shaft in Africa', year: 1973 },
  { name: 'Tous les matins du monde', year: 1991 },
  { name: 'Mr. Klein', year: 1976 },
  { name: 'Titicut Follies', year: 1967 },
  { name: 'The Drawn Together Movie: The Movie!', year: 2010 },
  { name: 'Gandu', year: 2010 },
  { name: 'Quiet Days in Clichy', year: 1970 },
  { name: 'Lucky Bastard', year: 2014 },
  { name: 'Cobra Verde', year: 1987 },
  { name: 'Going Under', year: 2004 },
  { name: 'Sexcula', year: 1974 },
  { name: 'Sade', year: 2000 },
  { name: 'Town & Country', year: 2001 },
  { name: 'Sleep with Me', year: 1994 },
  { name: 'Howl', year: 2010 },
  { name: 'The Safety of Objects', year: 2001 },
  { name: 'Homework', year: 1991 },
  { name: 'House of D', year: 2004 },
  { name: 'Get Real', year: 1998 },
  { name: 'Speaking of Sex', year: 2001 },
  { name: 'In the Basement', year: 2014 },
  { name: 'The Raspberry Reich', year: 2004 },
  { name: "The Monkey's Mask", year: 2000 },
  { name: 'The Secret Life of Words', year: 2005 },
  { name: 'Pornopung', year: 2013 },
  { name: 'Burning Man (I)', year: 2011 },
  { name: 'Kolya', year: 1996 },
  { name: 'Liberty Heights', year: 1999 },
  { name: 'Flesh', year: 1968 },
  { name: 'Sonny', year: 2002 },
  { name: 'Art History', year: 2011 },
  { name: 'Itty Bitty Titty Committee', year: 2007 },
  { name: 'Neon Heart', year: 2018 },
  { name: 'Subconscious Cruelty', year: 2000 },
  { name: 'Eating Out: All You Can Eat', year: 2009 },
  { name: 'Capriccio', year: 1987 },
  { name: 'Sol Goode', year: 2003 },
  { name: 'Uncle Kent', year: 2011 },
  { name: 'Emmanuelle 3', year: 1977 },
  { name: 'Feed', year: 2005 },
  { name: 'The Exotic House of Wax', year: 1997 },
  { name: 'The Dangerous Lives of Altar Boys', year: 2002 },
  { name: 'Freeway II: Confessions of a Trickbaby', year: 1999 },
  { name: '1969', year: 1988 },
  { name: 'Night of Something Strange', year: 2016 },
  { name: 'Head On', year: 1998 },
  { name: 'Goodbye Seventies', year: 2020 },
  { name: 'Killer Condom', year: 1996 },
  { name: 'Earth', year: 1998 },
  { name: 'Breaking Wind', year: 2012 },
  { name: 'Shadowboxer', year: 2005 },
  { name: 'The Living Dead Girl', year: 1982 },
  { name: 'Wadd: The Life & Times of John C. Holmes', year: 1999 },
  { name: 'Obscene: The Case of Peter Herzl', year: 1981 },
  { name: 'Atanarjuat: The Fast Runner', year: 2001 },
  { name: 'Schramm', year: 1993 },
  { name: 'The Enemy', year: 2020 },
  { name: 'Sicario', year: 1994 },
  { name: 'Behind Blue Skies', year: 2010 },
  { name: 'The Outing', year: 1987 },
  { name: 'Sordid Lives', year: 2000 },
  { name: 'Cry Uncle', year: 1971 },
  { name: 'The Student', year: 2016 },
  { name: 'Japón', year: 2002 },
  { name: 'La teta asustada', year: 2009 },
  { name: '3 Generations', year: 2015 },
  { name: 'Sex Is Comedy', year: 2002 },
  { name: 'Dear Wendy', year: 2005 },
  { name: 'No Reason', year: 2010 },
  { name: 'When Father Was Away on Business', year: 1985 },
  { name: 'Borderline', year: 2008 },
  { name: 'Kissing on the Mouth', year: 2005 },
  { name: 'Longhorns', year: 2011 },
  { name: 'Paris, France', year: 1993 },
  { name: 'Murderball', year: 2005 },
  { name: 'Lovers: A True Story', year: 1991 },
  { name: 'Babysitting 2', year: 2015 },
  { name: 'Spermula', year: 1976 },
  { name: 'Phantom Love', year: 2000 },
  { name: 'Deported Women of the SS Special Section', year: 1976 },
  { name: 'The Ornithologist', year: 2016 },
  { name: 'Porn Star: The Legend of Ron Jeremy', year: 2001 },
  { name: 'Bunny the Killer Thing', year: 2015 },
  { name: 'Wicked Women', year: 1978 },
  { name: 'American Swing', year: 2008 },
  { name: 'Tristram Shandy', year: 2005 },
  { name: 'The Fluffer', year: 2001 },
  { name: 'Venus in Furs', year: 1994 },
  { name: 'Inhibitions', year: 1976 },
  { name: 'A Somewhat Gentle Man', year: 2010 },
  { name: 'The Green Elephant', year: 1999 },
  { name: 'Shank', year: 2009 },
  { name: 'A Hole in My Heart', year: 2004 },
  { name: 'Sennentuntschi: Curse of the Alps', year: 2010 },
  { name: 'Gadjo dilo', year: 1997 },
  { name: 'Floating Skyscrapers', year: 2013 },
  { name: 'Fateless', year: 2005 },
  { name: 'Box of Moonlight', year: 1996 },
  { name: 'Swung', year: 2015 },
  { name: 'Hardcore', year: 2004 },
  { name: 'Please Give', year: 2010 },
  { name: 'Eight Miles High', year: 2007 },
  { name: 'Little Deaths', year: 2011 },
  { name: 'A Decent Woman', year: 2016 },
  { name: 'The Mansion', year: 2017 },
  { name: 'The Godson', year: 1971 },
  { name: 'My Man', year: 1996 },
  { name: 'Medeas', year: 2013 },
  { name: 'Rudo y Cursi', year: 2008 },
  { name: 'Bad Company', year: 1995 },
  { name: 'Heading South', year: 2005 },
  { name: 'Un + une', year: 2015 },
  { name: 'King Jack', year: 2015 },
  { name: "The Devil's Playground", year: 1976 },
  { name: 'The Vicious Kind', year: 2009 },
  { name: 'Turn Me On, Dammit!', year: 2011 },
  { name: 'Night Terrors', year: 1993 },
  { name: 'Best Night Ever', year: 2013 },
  { name: 'Tiger Orange', year: 2014 },
  { name: 'You & I', year: 2014 },
  { name: 'Mad Foxes', year: 1981 },
  { name: 'Sitcom', year: 1998 },
  { name: 'The Real Cancun', year: 2003 },
  { name: 'Faust (III)', year: 2011 },
  { name: 'Zappa', year: 1983 },
  { name: 'Eisenstein in Guanajuato', year: 2015 },
  { name: 'Snatch', year: 1976 },
  { name: 'Romeos', year: 2011 },
  { name: 'La fille sur le pont', year: 1999 },
  { name: 'The Good Mother', year: 1988 },
  { name: 'Halfaouine: Boy of the Terraces', year: 1990 },
  { name: 'Casa privata per le SS', year: 1977 },
  { name: 'The Star Maker', year: 1995 },
  { name: 'Our RoboCop Remake', year: 2014 },
  { name: 'Interior. Leather Bar.', year: 2013 },
  { name: 'Neighboring Sounds', year: 2012 },
  { name: 'Chattahoochee', year: 1989 },
  { name: 'A Curtain Raiser & Other Shorts', year: 2007 },
  { name: 'Picking Up the Pieces', year: 2000 },
  { name: 'Quinceañera', year: 2006 },
  { name: 'Walk on Water', year: 2004 },
  { name: 'Juan of the Dead', year: 2011 },
  { name: 'Text', year: 2019 },
  { name: 'Calendar Girl', year: 1993 },
  { name: 'The Singing Forest', year: 2003 },
  { name: 'Trash', year: 1970 },
  { name: "My Father's Glory", year: 1990 },
  { name: 'The Other Side of the Bed', year: 2002 },
  { name: 'Carcinoma', year: 2014 },
  { name: 'Not Cool (II)', year: 2014 },
  { name: 'The Governess', year: 1998 },
  { name: 'Garçon stupide', year: 2004 },
  { name: 'The Maid', year: 2009 },
  { name: 'Chevalier', year: 2015 },
  { name: 'Last Life in the Universe', year: 2003 },
  { name: 'Crazy Right', year: 2018 },
  { name: 'Tiresia', year: 2003 },
  { name: 'Fantasm Comes Again', year: 1977 },
  { name: 'Bizarre', year: 2015 },
  { name: 'Mouth to Mouth', year: 1995 },
  { name: 'Psychomagic, A Healing Art', year: 2019 },
  { name: 'Bad President', year: 2021 },
  { name: 'Fatso', year: 2008 },
  { name: 'Fat Girls', year: 2006 },
  { name: 'Ted & Venus', year: 1991 },
  { name: 'Of Skin and Men', year: 2017 },
  { name: 'How to Be a Man', year: 2013 },
  { name: 'Last Rites', year: 1988 },
  { name: "Lola's Secret", year: 1984 },
  { name: 'Hustler White', year: 1996 },
  { name: 'Divorce Club', year: 2020 },
  { name: 'The Demoniacs', year: 1974 },
  { name: 'Matrubhoomi: A Nation Without Women', year: 2003 },
  { name: 'Dead Europe', year: 2012 },
  { name: 'La casa de las mujeres perdidas', year: 1983 },
  { name: 'French Twist', year: 1995 },
  { name: 'Short Skin', year: 2014 },
  { name: 'Me and Him', year: 1988 },
  { name: "When You're Strange", year: 2009 },
  { name: "Summer '04", year: 2006 },
  { name: 'Wieners', year: 2008 },
  { name: 'The Kindergarten Teacher', year: 2014 },
  { name: 'Bloom (I)', year: 2003 },
  { name: 'Boy in a Bathtub', year: 2006 },
  { name: 'Drown (I)', year: 2015 },
  { name: 'Close Enough to Touch', year: 2002 },
  { name: 'Saint Ralph', year: 2004 },
  { name: 'Hotel St. Pauli', year: 1988 },
  { name: 'Maslin Beach', year: 1997 },
  { name: 'White Coats', year: 2004 },
  { name: 'Five (I)', year: 2016 },
  { name: 'Sechs Schwedinnen auf der Alm', year: 1983 },
  { name: 'Secret Games 3', year: 1994 },
  { name: 'Sexual Tension: Volatile', year: 2012 },
  { name: 'Threesome', year: 2014 },
  { name: 'American Guinea Pig: Sacrifice', year: 2017 },
  { name: 'Evilenko', year: 2003 },
  { name: 'Billy Boy (I)', year: 2017 },
  { name: 'Fluidø', year: 2017 },
  { name: 'The Sentimental Education of Eugénie', year: 2005 },
  { name: 'Taxi zum Klo', year: 1980 },
  { name: 'Murder Syndrome', year: 1981 },
  { name: 'He Loves Me', year: 2018 },
  { name: 'Angels with Dirty Wings', year: 2009 },
  { name: 'Divine Love', year: 2019 },
  { name: 'DAU. Natasha', year: 2020 },
  { name: 'Goltzius and The Pelican Company', year: 2012 },
  { name: 'Utopians', year: 2015 },
  { name: 'Entrails of a Virgin', year: 1986 },
  { name: 'Mondo Weirdo', year: 1990 },
  { name: 'Edges of the Lord', year: 2001 },
  { name: 'NSFW: Not Safe for Work', year: 2014 },
  { name: 'José (II)', year: 2018 },
  { name: 'Wild Side', year: 2004 },
  { name: 'Up the Sandbox', year: 1972 },
  { name: 'Klown Forever', year: 2015 },
  { name: 'Surrender Dorothy', year: 1998 },
  { name: 'Ten Canoes', year: 2006 },
  { name: 'Despite the Night', year: 2015 },
  { name: 'Flirt', year: 1995 },
  { name: 'Christina', year: 1984 },
  { name: 'Memento Mori', year: 1999 },
  { name: 'Twice Upon a Yesterday', year: 1998 },
  { name: 'Agnes Browne', year: 1999 },
  { name: 'Peep World', year: 2010 },
  { name: 'The Hypnotized', year: 2004 },
  { name: 'Torment (VII)', year: 2017 },
  { name: 'The Endless Possibility of Sky', year: 2012 },
  { name: 'Ur kärlekens språk', year: 1969 },
  { name: 'Wild Awakening', year: 2016 },
  { name: 'La bella e la bestia', year: 1977 },
  { name: 'DAU. New Man', year: 2020 },
  { name: 'Fetishes', year: 1996 },
  { name: 'The Other Side (VIII)', year: 2015 },
  { name: 'Three Dancing Slaves', year: 2004 },
  { name: 'Yossi', year: 2012 },
  { name: '3-Day Weekend', year: 2008 },
  { name: 'Emperor Tomato Ketchup', year: 1971 },
  { name: "Fortune and Men's Eyes", year: 1971 },
  { name: 'Kala azar', year: 2020 },
  { name: 'Serbis', year: 2008 },
  { name: 'Foam Party!', year: 2017 },
  { name: 'Pendular', year: 2017 },
  { name: "Georges Bataille's Story of the Eye", year: 2003 },
  { name: 'Frank McKlusky, C.I.', year: 2002 },
  { name: 'Aaaaaaaah!', year: 2015 },
  { name: '3some', year: 2009 },
  { name: 'Beware the Gonzo', year: 2010 },
  { name: 'Scotty and the Secret History of Hollywood', year: 2017 },
  { name: 'What Is It?', year: 2005 },
  { name: "Mords pas, on t'aime!", year: 1976 },
  { name: 'Jonathan Agassi Saved My Life', year: 2018 },
  { name: 'Papaya: Love Goddess of the Cannibals', year: 1978 },
  { name: 'All That Matters Is Past', year: 2012 },
  { name: 'Les textiles', year: 2004 },
  { name: 'Sex, Drugs & Taxation', year: 2013 },
  { name: 'Mandragora', year: 1997 },
  { name: 'Drink Me', year: 2015 },
  { name: 'A Chinese Torture Chamber Story', year: 1994 },
  { name: "D'Agostino", year: 2012 },
  { name: 'Supernatural', year: 2014 },
  { name: 'Rat Fever', year: 2011 },
  { name: 'Strip Club Massacre', year: 2017 },
  { name: 'The Orgasm Diaries', year: 2010 },
  { name: 'Build the Wall', year: 2020 },
  { name: 'La rabia', year: 2008 },
  { name: 'Over the Wire', year: 1996 },
  { name: 'Enormous', year: 2019 },
  { name: 'The Future Is Woman', year: 1984 },
  { name: 'My Sex Life... or How I Got Into an Argument', year: 1996 },
  { name: 'Stronghold', year: 1985 },
  { name: 'August Winds', year: 2014 },
  { name: 'The Crossing', year: 2004 },
  { name: 'Amateur Porn Star Killer', year: 2006 },
  { name: 'Chain of Desire', year: 1992 },
  { name: 'Tattoo', year: 2013 },
  { name: 'Reprimidos', year: 2004 },
  { name: 'What Do You Say to a Naked Lady?', year: 1970 },
  { name: 'Diary of a Maniac', year: 1993 },
  { name: 'Frank & Eva', year: 1973 },
  { name: 'The Eternal Evil of Asia', year: 1995 },
  { name: 'Tinta Bruta', year: 2018 },
  { name: 'Catch Your Dreams', year: 1983 },
  { name: 'Greek Pete', year: 2009 },
  { name: "Molly's Theory of Relativity", year: 2013 },
  { name: 'In the Realms of the Unreal', year: 2004 },
  { name: 'India Blues: Eight Feelings', year: 2013 },
  { name: 'Lulu on the Bridge', year: 1998 },
  { name: 'Scarred Hearts', year: 2016 },
  { name: 'I Am Happiness on Earth', year: 2014 },
  { name: 'Nanami: The Inferno of First Love', year: 1968 },
  { name: 'I Kissed a Girl', year: 2015 },
  { name: 'Nackt', year: 2002 },
  { name: 'Trapped Ashes', year: 2006 },
  { name: 'Tiffany, i agriogata tou erota', year: 1985 },
  { name: 'UnHung Hero', year: 2013 },
  { name: 'Porno (I)', year: 2013 },
  { name: 'Última Parada 174', year: 2008 },
  { name: '20 centímetros', year: 2005 },
  { name: 'American Translation', year: 2011 },
  { name: 'Uncut', year: 2003 },
  { name: 'Una noche', year: 2012 },
  { name: 'I Can Quit Whenever I Want', year: 2019 },
  { name: 'La meilleure façon de marcher', year: 1976 },
  { name: 'Antarctica', year: 2008 },
  { name: "Satan's Brew", year: 1976 },
  { name: "Canciones de amor en Lolita's Club", year: 2007 },
  { name: 'Paranormal Sex Tape', year: 2016 },
  { name: 'Year of the Carnivore', year: 2009 },
  { name: 'Like a Brother', year: 2005 },
  { name: 'Johns', year: 1996 },
  { name: 'Standard Operating Procedure', year: 2008 },
  { name: 'Skylab', year: 2011 },
  { name: 'The Terrorists', year: 2011 },
  { name: 'Let Me Die a Woman', year: 1977 },
  { name: 'Barefoot to the Neck', year: 2009 },
  { name: 'Street of No Return', year: 1989 },
  { name: 'Whatever', year: 1999 },
  { name: 'Die 120 Tage von Bottrop', year: 1997 },
  { name: 'The Sadist of Notre Dame', year: 1979 },
  { name: 'Rape Zombie: Lust of the Dead 2', year: 2013 },
  { name: 'The Consul of Sodom', year: 2009 },
  { name: 'Escaping Freedom', year: 2020 },
  { name: 'Die Geschichte vom weinenden Kamel', year: 2003 },
  { name: 'Erotiki teleti', year: 1979 },
  { name: 'Mapplethorpe: Look at the Pictures', year: 2016 },
  { name: 'Remedy (I)', year: 2013 },
  { name: 'Mai mee Samui samrab ter', year: 2017 },
  { name: 'Kings & Queen', year: 2004 },
  { name: 'Dark Mountain', year: 2013 },
  { name: 'Big Like Me', year: 2014 },
  { name: 'Die, Mommie, Die!', year: 2003 },
  { name: 'Once Upon a Time Veronica', year: 2012 },
  { name: '(Untitled)', year: 2009 },
  { name: 'La vie sexuelle des Belges 1950-1978', year: 1994 },
  { name: 'Live Feed', year: 2006 },
  { name: 'Uncertain Glory', year: 2017 },
  { name: 'Velvet Dreams', year: 1988 },
  { name: 'The Tulse Luper Suitcases, Part 1: The Moab Story', year: 2003 },
  { name: 'Baixio das Bestas', year: 2006 },
  { name: 'Cachorro', year: 2004 },
  { name: 'Documenteur', year: 1981 },
  { name: 'Sextape', year: 2018 },
  { name: 'Numéro deux', year: 1975 },
  { name: 'Celestine, Maid at Your Service', year: 1974 },
  { name: 'Persécution', year: 2009 },
  { name: 'Love and Other Catastrophes', year: 1996 },
  { name: 'Spork', year: 2010 },
  { name: 'Zenabel', year: 1969 },
  { name: 'Teenage Playmates', year: 1974 },
  { name: 'Sugar (I)', year: 2004 },
  { name: 'The End of Cruising', year: 2013 },
  { name: 'Hopla på sengekanten', year: 1976 },
  { name: 'Nefeli', year: 1980 },
  { name: 'Girls Will Be Girls', year: 2003 },
  { name: 'House of Fools', year: 2002 },
  { name: 'Winter Brothers', year: 2017 },
  { name: 'The Boys & Girl from County Clare', year: 2003 },
  { name: 'Mother Schmuckers', year: 2021 },
  { name: "Joe Gould's Secret", year: 2000 },
  { name: 'Der freie Wille', year: 2006 },
  { name: 'Police des moeurs: Les filles de Saint Tropez', year: 1987 },
  { name: 'The Hanging Garden', year: 1997 },
  { name: 'I Am a Sex Addict', year: 2005 },
  { name: 'Arranged Marriage', year: 1996 },
  { name: 'In Their Room: Berlin', year: 2011 },
  { name: 'The Family Complete', year: 2010 },
  { name: 'Models', year: 1999 },
  { name: 'Doll Syndrome', year: 2014 },
  { name: 'Cold Feet', year: 2018 },
  { name: 'La confusion des genres', year: 2000 },
  { name: 'Rio Babilonia', year: 1982 },
  { name: 'Fabian', year: 1980 },
  { name: 'Beautiful Youth', year: 2014 },
  { name: 'Sworn Virgin', year: 2015 },
  { name: 'Phantasmagoria (I)', year: 2014 },
  { name: 'Bawdy Tales', year: 1973 },
  { name: 'Murder Me, Monster', year: 2018 },
  { name: 'The Designated Mourner', year: 1997 },
  { name: 'Like Cattle Towards Glow', year: 2015 },
  { name: "The Skin I'm In", year: 2012 },
  { name: "Antonio's Secret", year: 2008 },
  { name: "Hyde's Secret Nightmare", year: 2011 },
  { name: 'Proteus', year: 2003 },
  { name: 'The Velocity of Gary', year: 1998 },
  { name: 'Cuentos eróticos', year: 1980 },
  { name: 'A Perfect Fit', year: 2005 },
  { name: 'Wrong Way', year: 1972 },
  { name: 'Strange Planet', year: 1999 },
  { name: "Boy Eating the Bird's Food", year: 2012 },
  { name: 'Tied', year: 2013 },
  { name: 'DAU. Degeneratsiya', year: 2020 },
  { name: 'Faultless', year: 2016 },
  { name: 'Triple Crossed', year: 2013 },
  { name: 'Tag der Idioten', year: 1981 },
  { name: 'On Edge', year: 2001 },
  { name: 'Answers to Nothing', year: 2011 },
  { name: 'The Turn of the Screw', year: 1992 },
  { name: 'Raging Sun, Raging Sky', year: 2009 },
  { name: "Don't Love Me", year: 2017 },
  { name: 'Guddu Ki Gun', year: 2015 },
  { name: 'Miserere', year: 2019 },
  { name: "O'Horten", year: 2007 },
  { name: 'Zauberer', year: 2018 },
  { name: 'Der Samurai', year: 2014 },
  { name: 'Shadowzone', year: 1990 },
  { name: 'Wetlands', year: 2011 },
  { name: 'A Spiral of Mist', year: 1977 },
  { name: 'Pizza, Beer, and Cigarettes', year: 1998 },
  { name: 'Trumbo', year: 2007 },
  { name: 'Alien Crystal Palace', year: 2018 },
  { name: 'Testosterone', year: 2003 },
  { name: 'Half Brother', year: 2018 },
  { name: 'A Scream in the Streets', year: 1973 },
  { name: 'Notre Dame', year: 2019 },
  { name: 'Joaquim', year: 2017 },
  { name: 'Love in the Time of Money', year: 2002 },
  { name: 'Stonewall', year: 1995 },
  { name: 'Accomplices', year: 2009 },
  { name: 'No Way Out', year: 2008 },
  { name: 'Playa azul', year: 1982 },
  { name: 'The King of Masks', year: 1996 },
  { name: 'Lola and Billy the Kid', year: 1999 },
  { name: 'Happenstance', year: 2000 },
  { name: 'Big Bad Love', year: 2001 },
  { name: 'Lucía, Lucía', year: 2003 },
  { name: 'Something Must Break', year: 2014 },
  { name: '4 Days in France', year: 2016 },
  { name: 'Gabi on the Roof in July', year: 2010 },
  { name: 'The Naked Peacock', year: 1975 },
  { name: 'The Blue Flower of Novalis', year: 2018 },
  { name: 'Rock Haven', year: 2007 },
  { name: 'Primo Basílio', year: 2007 },
  { name: 'The Baby Formula', year: 2008 },
  { name: 'Desnudos', year: 2004 },
  { name: 'Cilveka berns', year: 1992 },
  { name: 'Vampire Boys 2: The New Brood', year: 2013 },
  { name: 'Treasure Island (I)', year: 1999 },
  { name: 'The Sixth Time', year: 2017 },
  { name: 'To the Extreme', year: 2000 },
  { name: 'Billy Boy', year: 1970 },
  { name: 'Shadow People (I)', year: 2007 },
  { name: 'Breathing', year: 2011 },
  { name: 'Silent Lies', year: 1996 },
  { name: 'Lakeboat', year: 2000 },
  { name: 'Falling Star', year: 2014 },
  { name: 'Public Eye', year: 2021 },
  { name: 'A Woman Called Sada Abe', year: 1975 },
  { name: 'Oi tembelides tis eforis koiladas', year: 1978 },
  { name: 'Vegas', year: 2009 },
  { name: 'The Night of the Virgin', year: 2016 },
  { name: 'Ferozz: The Wild Red Riding Hood', year: 2010 },
  { name: 'Swans', year: 2011 },
  { name: 'Dragon Ball: The Path to Power', year: 1996 },
  { name: 'Uncle Sasha', year: 2018 },
  { name: 'Streaker', year: 2017 },
  { name: 'Tender and Perverse Emanuelle', year: 1973 },
  { name: 'Broken Sky', year: 2006 },
  { name: 'The Slingshot', year: 1993 },
  { name: 'Underwater Love', year: 2011 },
  { name: 'Les maris, les femmes, les amants', year: 1989 },
  { name: 'Acid', year: 2018 },
  { name: "All God's Children Can Dance", year: 2008 },
  { name: '15: The Movie', year: 2003 },
  { name: 'My Guy', year: 2018 },
  { name: "L'ennemi naturel", year: 2004 },
  { name: 'Living on Love Alone', year: 2010 },
  { name: 'A Leap in the Dark', year: 1980 },
  { name: 'Luz del Fuego', year: 1982 },
  { name: 'Leviatan', year: 2016 },
  { name: 'Voodoo', year: 2007 },
  { name: 'Heat Wave', year: 2011 },
  { name: 'Moonshine Meat Market Mayhem', year: 2016 },
  { name: 'Allein', year: 2004 },
  { name: 'Spanish Fly', year: 1998 },
  { name: 'The Dickumentary', year: 2014 },
  { name: 'Inclinación sexual al desnudo', year: 1982 },
  { name: 'Das Flüstern des Mondes', year: 2006 },
  { name: 'The Inheritors', year: 1998 },
  { name: 'Dona Flor and Her Two Husbands', year: 2017 },
  { name: 'Twisted Romance', year: 2008 },
  { name: 'The Mark of Cain', year: 2007 },
  { name: 'Neigh Means Yes', year: 1991 },
  { name: 'Karina, Objeto do Prazer', year: 1982 },
  { name: '7 Sins (II)', year: 2020 },
  { name: 'Reincarnate', year: 2010 },
  { name: '24/7: The Passion of Life', year: 2005 },
  { name: 'Cowards Bend the Knee', year: 2003 },
  { name: 'Age of Consent', year: 2014 },
  { name: 'Vaiburêta', year: 2003 },
  { name: 'Little Sharks', year: 1992 },
  { name: 'Museum Hours', year: 2012 },
  { name: 'Savana - Sesso e diamanti', year: 1978 },
  { name: 'I Dreamt Under the Water', year: 2008 },
  { name: "David Holzman's Diary", year: 1967 },
  { name: 'The Architect', year: 2008 },
  { name: 'ErOddity(s) 2', year: 2015 },
  { name: 'Is There Sex After Death?', year: 1971 },
  { name: 'Park (I)', year: 2016 },
  { name: 'Tikkun', year: 2015 },
  { name: "Nuit d'été en ville", year: 1990 },
  { name: 'Sada', year: 1998 },
  { name: 'Hardkor Disko', year: 2014 },
  { name: 'Hara Kiri', year: 2016 },
  { name: 'Angels with Tethered Wings', year: 2014 },
  { name: 'The Gays', year: 2014 },
  { name: 'Dirty World', year: 1978 },
  { name: 'Nous étions un seul homme', year: 1979 },
  { name: 'Five (I)', year: 2010 },
  { name: 'The Taint', year: 2011 },
  { name: 'The Wrong Ferarri', year: 2011 },
  { name: 'Father & Son', year: 2015 },
  { name: 'Shocking Africa', year: 1982 },
  { name: "Anderson's Cross", year: 2010 },
  { name: 'Cages', year: 2006 },
  { name: 'Futz', year: 1969 },
  { name: 'Il cielo cade', year: 2000 },
  { name: 'Achtung, fertig, Charlie!', year: 2003 },
  { name: 'Bloody Sin (I)', year: 2011 },
  { name: 'Scandal: Body of Love', year: 2000 },
  { name: 'The Conviction', year: 1991 },
  { name: 'This Space Between Us', year: 1999 },
  { name: 'Full Speed', year: 1996 },
  { name: 'New Wave', year: 1983 },
  { name: 'The Distance', year: 2006 },
  { name: 'Mes séances de lutte', year: 2013 },
  { name: 'Deseo carnal', year: 1978 },
  { name: 'Spin the Bottle', year: 1998 },
  { name: 'Quello strano desiderio', year: 1979 },
  { name: 'A Complete History of My Sexual Failures', year: 2008 },
  { name: 'Les chatouilleuses', year: 1975 },
  { name: 'Homosexual', year: 2013 },
  { name: 'Joves', year: 2004 },
  { name: 'Love, Ludlow', year: 2005 },
  { name: 'The Château', year: 2001 },
  { name: 'Village of Dreams', year: 1996 },
  { name: 'News from Planet Mars', year: 2016 },
  { name: 'Federico García Lorca Noir Despair', year: 2013 },
  { name: 'Un enfant dans la foule', year: 1976 },
  { name: 'Bacanal en directo', year: 1979 },
  { name: 'Orfeu', year: 1999 },
  { name: 'Bible!', year: 1974 },
  { name: 'Maybe', year: 1999 },
  { name: 'Daphnis and Chloe', year: 1993 },
  { name: "I'll Never Die Alone", year: 2008 },
  { name: 'All Male, All Nude', year: 2017 },
  { name: 'Mesto na zemle', year: 2001 },
  { name: 'Ice Blues', year: 2008 },
  { name: 'Erotic Salad', year: 1967 },
  { name: 'Wound', year: 2010 },
  { name: 'Sikil', year: 2008 },
  { name: 'The Weight', year: 2012 },
  { name: 'Gift from Above', year: 2003 },
  { name: 'Wild Romance', year: 2006 },
  { name: 'Le chien', year: 2007 },
  { name: 'Porno de autor', year: 2010 },
  { name: 'Blue Nude', year: 1978 },
  { name: 'Speed of Life', year: 1999 },
  { name: "Zombie '90: Extreme Pestilence", year: 1991 },
  { name: 'Infidélités', year: 1975 },
  { name: 'Kill the Moonlight', year: 1994 },
  { name: 'Africa Uncensored', year: 1971 },
  { name: 'Deadly Screams of a Naked Siren', year: 2019 },
  { name: 'Female Inquisitor', year: 1987 },
  { name: 'Transfixed', year: 2001 },
  { name: 'Bazar', year: 2009 },
  { name: 'Breakdown', year: 1978 },
  { name: 'Luna di sangue', year: 1989 },
  { name: 'Fulboy', year: 2015 },
  { name: 'The Business of Fancydancing', year: 2002 },
  { name: "I'm All Yours", year: 2015 },
  { name: 'Trembling Before G-d', year: 2001 },
  { name: 'Prenez la queue comme tout le monde', year: 1973 },
  { name: 'Himlen falder', year: 2009 },
  { name: 'Kärlekens XYZ', year: 1971 },
  { name: 'Le jouisseur', year: 1975 },
  { name: 'The Go-Getters', year: 2018 },
  { name: 'Mon bel amour, ma déchirure', year: 1987 },
  { name: 'Hide and Seek', year: 1996 },
  { name: 'Gore Whore', year: 1994 },
  { name: 'The Philosopher', year: 1989 },
  { name: 'Idiot Love', year: 2004 },
  { name: 'Mujeres Infieles', year: 2004 },
  { name: 'The Diary of Lady M', year: 1993 },
  { name: 'Wasted!', year: 1996 },
  { name: 'Bikers', year: 2017 },
  { name: 'Quick Change', year: 2013 },
  { name: 'Càlamo', year: 1976 },
  { name: 'The Inseminator', year: 2014 },
  { name: "My Life's in Turnaround", year: 1993 },
  { name: 'What Now? Remind Me', year: 2013 },
  { name: 'Crustacean', year: 2009 },
  { name: 'Too Hard to Handle', year: 2016 },
  { name: 'Cock & Bull Story', year: 2002 },
  { name: 'Man of the Year', year: 1995 },
  { name: 'I Love Snuff', year: 1995 },
  { name: 'Les confidences de Sandra', year: 1973 },
  { name: 'My Scary Girl', year: 2006 },
  { name: 'The Triumph of Sodom', year: 2020 },
  { name: 'Zus & Zo', year: 2001 },
  { name: 'Fanatics', year: 2012 },
  { name: "Dorothea's Rache", year: 1974 },
  { name: 'A golpes', year: 2005 },
  { name: 'eXXXorcisms', year: 2002 },
  { name: 'Siberia', year: 1998 },
  { name: 'O Gosto do Pecado', year: 1980 },
  { name: 'Single Plus', year: 2012 },
  { name: 'Floaty', year: 2021 },
  { name: 'Videophilia (and Other Viral Syndromes)', year: 2015 },
  { name: 'Ashes from the Sky', year: 2008 },
  { name: 'Before the Night Is Over', year: 2020 },
  { name: 'Batguano', year: 2014 },
  { name: 'Dirty Romance', year: 2015 },
  { name: 'Chickboxer', year: 1992 },
  { name: 'Kotiteollisuus - Leirituomiolla', year: 2016 },
  { name: 'Smeker', year: 1986 },
  { name: 'Pierrot Lunaire', year: 2014 },
  { name: 'O Caminho das Nuvens', year: 2003 },
  { name: 'Tarzun and the Valley of Lust', year: 1970 },
  { name: 'Magikos kathreftis', year: 2016 },
  { name: 'All the Cities of the North', year: 2016 },
  { name: 'The Ungovernable Force', year: 2015 },
  { name: 'A Silent Agreement', year: 2017 },
  { name: 'De Lama Lamina', year: 2007 },
  { name: 'The Delivery', year: 1999 },
  { name: 'Crime Delicado', year: 2005 },
  { name: 'Skavabölen pojat', year: 2009 },
  { name: 'Kiss and Cry (II)', year: 2017 },
  { name: 'Cronicamente Inviável', year: 2000 },
  { name: 'Sans Elle...', year: 2003 },
  { name: 'The Pisciotta Case', year: 1972 },
  { name: 'A Corsican Summer', year: 2021 },
  { name: 'Hombre (II)', year: 2017 },
  { name: 'Keillers park', year: 2006 },
  { name: "Being Two Isn't Easy", year: 1962 },
  { name: 'Syndare i sommarsol', year: 2001 },
  { name: 'Straight & Butch', year: 2010 },
  { name: 'Flirting with Anthony', year: 2005 },
  { name: 'Desenfrenos carnales', year: 1982 },
  { name: 'Doggiewoggiez! Poochiewoochiez!', year: 2012 },
  { name: 'Another Man', year: 2008 },
  { name: 'Meiji · Taishô · Shôwa: Ryôki onna hanzai-shi', year: 1969 },
  { name: 'Frente Al Mar', year: 1978 },
  { name: 'Let the Old Folks Die', year: 2017 },
  { name: 'Rezubian hâremu', year: 1987 },
  { name: 'Lady Macbeth von Mzensk', year: 1992 },
  { name: 'The Cocktail Hostesses', year: 1973 },
  { name: 'Everything Will Happen Before You Die', year: 2010 },
  { name: "Bigger Like Me (Extended Director's Cut)", year: 2019 },
  { name: 'Belmonte', year: 2018 },
  { name: 'Senn', year: 2013 },
  { name: 'Dark Waves', year: 2015 },
  { name: 'Life Pornography', year: 2003 },
  { name: 'The Nun and the Torturer', year: 1983 },
  { name: "Heaven's a Drag", year: 1994 },
  { name: "Christie Malry's Own Double-Entry", year: 2000 },
  { name: 'The Face of Medusa', year: 1967 },
  { name: 'Abel, Your Brother', year: 1970 },
  { name: 'Abe Sada: Saigo no nanokakan', year: 2011 },
  { name: 'Okoge', year: 1992 },
  { name: 'The Rebellion of Red Maria', year: 2011 },
  { name: 'Overdose of Degradation', year: 1970 },
  { name: 'The First Time of Brazilian Cinema', year: 2013 },
  { name: 'El último pecado de la burguesía', year: 1978 },
  { name: 'Pink Ulysses', year: 1990 },
  { name: 'Skin and Bone', year: 1996 },
  { name: 'Monique, mein heißer Schoß', year: 1978 },
  { name: 'Total Badass', year: 2010 },
  { name: 'C.I.A.', year: 2019 },
  { name: 'Uncle Bob', year: 2010 },
  { name: 'Central Bazaar', year: 1976 },
  { name: 'Las esclavas del sadismo', year: 1994 },
  { name: 'La Pasión de Michelangelo', year: 2013 },
  { name: 'Hahithalfut', year: 2011 },
  { name: 'Les couples du Bois de Boulogne', year: 1974 },
  { name: 'Urinal', year: 1988 },
  { name: 'Verde verde', year: 2012 },
  { name: 'La memoria de los peces', year: 2004 },
  { name: 'Only the Brave', year: 1994 },
  { name: 'P.O.E.: Project of Evil', year: 2012 },
  { name: "Ni d'Ève, ni d'Adam", year: 1996 },
  { name: 'The Passion of Berenice', year: 1976 },
  { name: 'The Bang Bang Gang', year: 1970 },
  { name: 'The Ghosts', year: 2018 },
  { name: 'Mujeres salvajes', year: 1984 },
  { name: 'Burning Annie', year: 2004 },
  { name: 'Venus in the Garden', year: 2011 },
  { name: 'The Real Body', year: 2000 },
  { name: 'Death on Demand', year: 2008 },
  { name: 'Frameup', year: 1993 },
  { name: 'The Clinic', year: 1982 },
  { name: 'Ixe', year: 1980 },
  { name: 'Heterosexualis', year: 1973 },
  { name: 'Campus Crush', year: 2009 },
  { name: "Impariamo ad amarci: guida all'educazione sessuale", year: 1985 },
  { name: 'She-Demons of the Black Sun', year: 2006 },
  { name: 'Gendernauts: A Journey Through Shifting Identities', year: 1999 },
  { name: 'Sambá', year: 2017 },
  { name: 'Verdict', year: 2005 },
  { name: 'Be Gentle, Penguin', year: 1982 },
  { name: 'Hippy Porn', year: 1991 },
  { name: 'Epokalipsa', year: 2019 },
  { name: 'Vera', year: 2003 },
  { name: 'Why Hast Thou Forsaken Me', year: 2015 },
  { name: 'El vuelo de la cigüeña', year: 1979 },
  { name: 'Chongqing', year: 2008 },
  { name: 'Wedding', year: 1989 },
  { name: 'Talking Dick', year: 2003 },
  { name: 'My Tomorrow', year: 2011 },
  { name: 'Er Moretto - Von Liebe leben', year: 1984 },
  { name: 'Movie: Marrying the Mafia 3 - Family Hustle', year: 2006 },
  { name: 'Beverly Kills', year: 2005 },
  { name: 'Neurosia: Fifty Years of Perversion', year: 1995 },
  { name: 'Donna Donna!!', year: 1987 },
  { name: '91.1', year: 2016 },
  { name: "What's It All About", year: 1995 },
  { name: 'Driving Bill Crazy', year: 2008 },
  { name: "Forget Everything I've Told You", year: 2002 },
  { name: 'El Perdido', year: 2016 },
  { name: 'Erkekler', year: 2013 },
  { name: 'Mirrors for Princes', year: 2011 },
  { name: 'Antropofaga Makumba', year: 2018 },
  { name: 'Mikri Arktos', year: 2015 },
  { name: 'La tentación', year: 1991 },
  { name: 'Blind Passion', year: 2004 },
  { name: 'Puppetry of the Penis: Tackle Happy', year: 2000 },
  { name: "Last Night at Eddie's", year: 1997 },
  { name: 'Private Lessons', year: 2009 },
  { name: 'Damned in the U.S.A.', year: 1992 },
  { name: 'Who Is KK Downey?', year: 2008 },
  { name: 'Mated', year: 1952 },
  { name: 'Maldita Coincidência', year: 1979 },
  { name: 'Beloved/Friend', year: 1999 },
  { name: 'Kenedi Is Getting Married', year: 2007 },
  { name: 'The Overbrook Brothers', year: 2009 },
  { name: 'O Seqüestro', year: 1981 },
  { name: 'Yi tan zhao yao jing zhi ying shao ming ce', year: 1996 },
  { name: 'Star Struck', year: 1996 },
  { name: 'Un negro con un saxo', year: 1989 },
  { name: 'The Young Hitchikers', year: 1971 },
  { name: 'Yes&Yes', year: 2014 },
  { name: 'The Unidentified', year: 2008 },
  { name: 'Ocana, an Intermittent Portrait', year: 1978 },
  { name: 'Walking with the Ferryman', year: 2014 },
  { name: 'Pie in the Sky: The Brigid Berlin Story', year: 2000 },
  { name: 'The Wild Hearts', year: 2008 },
  { name: "L'ombre d'une chance", year: 1974 },
  { name: 'El anticristo 2 (Magic London)', year: 1989 },
  { name: 'Bratya Ch', year: 2014 },
  { name: 'Romance', year: 1986 },
  { name: 'Because Why', year: 1993 },
  { name: 'Entraña', year: 2017 },
  { name: 'Tulipany', year: 2004 },
  { name: 'Guarani, People of the Selva', year: 2006 },
  { name: 'Fresh Starts 4 Stale People', year: 2011 },
  { name: 'Blood Rogues', year: 2009 },
  { name: 'Uzavreny Okruh', year: 1989 },
  { name: 'I am a Good Person/I Am a Bad Person', year: 2011 },
  { name: 'Zakochany aniol', year: 2005 },
  { name: 'The Grover Complex', year: 2010 },
  { name: 'Limites', year: 1995 },
  { name: 'LokalFilmis', year: 2015 },
  { name: 'Panic Bodies', year: 2003 },
  { name: 'Some Boys Do', year: 2010 },
  { name: 'Zuloak', year: 2012 },
  { name: "Laura's Room", year: 1988 },
  { name: "Blondie's Number One", year: 1971 },
  { name: 'Mezi námi práteli', year: 2006 },
  { name: 'Old Nick I', year: 2024 },
  { name: 'Stupne porazených', year: 1988 },
  { name: 'Approaches to the Psychology of Personality: Film No. 7', year: 1957 },
  { name: 'Body of God', year: 2013 },
];

export const search = (name: string, year: number) => {
  console.log(name, year);
  for (let i = 0; i < db.length; i++) {
    if (db[i].name.toLowerCase().includes(name) && db[i].year === year) {
      return true;
    }
  }
  return false;
};
